### ISSUE TITLE
`cf ssh` doesn't work for apps with rolling deployment

### ISSUE THREAD

**Issue by JimmyMa** [cloudfoundry/diego-ssh#46]
Here is rolling app deployment: https://docs.cloudfoundry.org/devguide/deploy-apps/rolling-deploy.html.

# Problem reproducing steps:

cf version 6.46.0+29d6257f1.2019-07-09

```
cf v3-zdt-push test_app

cf ssh test_app  # this works fine
cf v3-ssh test_app  # this works fine

cf v3-zdt-restart test_app

cf v3-ssh test_app  # this works fine
cf ssh test_app  # this doesn't work, with below error:
FAILED
Error opening SSH connection: ssh: handshake failed: ssh: unable to authenticate, attempted methods [none password], no supported methods remain
```

ssh_proxy has below error:

```
{"timestamp":"2019-11-20T02:34:24.444627044Z","level":"error","source":"ssh-proxy","message":"ssh-proxy.cf-authenticate.fetching-app-failed","data":{"ResponseBody":{},"StatusCode":"404 Not Found","app":"72eee5c5-5929-4142-a260-e2d3ccbe1172/0","error":"Fetching application data failed","principal":"3a867eb6-b1e4-4643-8eec-35fab32949b0","session":"1242","username":"xxxxx"}} 
```

cloud_controller_ng has below error:

```
Request failed: 404: {"description"=>"The app could not be found: 72eee5c5-5929-4142-a260-e2d3ccbe1172", "error_code"=>"CF-AppNotFound", "code"=>100004, "test_mode_info"=>{"description"=>"The app could not be found: 72eee5c5-5929-4142-a260-e2d3ccbe1172", "error_code"=>"CF-AppNotFound", "backtrace"=>["/var/vcap/data/packages/cloud_controller_ng/64f32046eec6c259eaa7fc931945599c5e566984/cloud_controller_ng/app/controllers/base/model_controller.rb:324:in `find_guid'", "/var/vcap/data/packages/cloud_controller_ng/64f32046eec6c259eaa7fc931945599c5e566984/cloud_controller_ng/app/controllers/base/model_controller.rb:317:in `find_guid_and_validate_access'", "/var/vcap/data/packages/cloud_controller_ng/64f32046eec6c259eaa7fc931945599c5e566984/cloud_controller_ng/app/controllers/runtime/apps_ssh_controller.rb:30:in `ssh_access_with_index'", "/var/vcap/data/packages/cloud_controller_ng/64f32046eec6c259eaa7fc931945599c5e566984/cloud_controller_ng/app/controllers/base/base_controller.rb:84:in `dispatch'", "/var/vcap/data/packages/cloud_controller_ng/64f32046eec6c259eaa7fc931945599c5e566984/cloud_controller_ng/lib/cloud_controller/rest_controller/routes.rb:16:in `block in define_route'", "/var/vcap/data/packages/cloud_controller_ng/64f32046eec6c259eaa7fc931945599c5e566984/gem_home/ruby/2.5.0/gems/sinatra-2.0.5/lib/sinatra/base.rb:1634:in `call'", "/var/vcap/data/packages/cloud_controller_ng/64f32046eec6c259eaa7fc931945599c5e566984/gem_home/ruby/2.5.0/gems/sinatra-2.0.5/lib/sinatra/base.rb:1634:in `block in compile!'", "/var/vcap/data/packages/cloud_controller_ng/64f32046eec6c259eaa7fc931945599c5e566984/gem_home/ruby/2.5.0/gems/sinatra-2.0.5/lib/sinatra/base.rb:992:in `block (3 
```

The root cause is that the command `cf v3-zdt-restart test_app` changed the `guid` of app process (for normal app, the app process `guid` and app `guid` is always same), so that CC could not find the app process.

The process `guid` of app `72eee5c5-5929-4142-a260-e2d3ccbe1172` is `13749565-ee33-4db3-a931-86229a76d1c5`, as below:

```
REQUEST: [2019-11-21T13:50:59+08:00]
GET /v3/apps/72eee5c5-5929-4142-a260-e2d3ccbe1172/processes HTTP/1.1
Host: xxxxxxxxxx
Accept: application/json
Authorization: [PRIVATE DATA HIDDEN]
User-Agent: cf/6.46.0+29d6257f1.2019-07-09 (go1.12.1; amd64 darwin)

RESPONSE: [2019-11-21T13:50:59+08:00]
HTTP/1.1 200 OK
Connection: Keep-Alive
Content-Type: application/json; charset=utf-8
Date: Thu, 21 Nov 2019 05:50:59 GMT
Referrer-Policy: strict-origin-when-cross-origin
Server: nginx
X-Xss-Protection: 1; mode=block
{
  "pagination": {
    "first": {
      "href": "https://xxxxxxx/v3/apps/72eee5c5-5929-4142-a260-e2d3ccbe1172/processes?page=1&per_page=50"
    },
    "last": {
      "href": "https://xxxxxxxx/v3/apps/72eee5c5-5929-4142-a260-e2d3ccbe1172/processes?page=1&per_page=50"
    },
    "next": null,
    "previous": null,
    "total_pages": 1,
    "total_results": 1
  },
  "resources": [
    {
      "command": "[PRIVATE DATA HIDDEN IN LISTS]",
      "created_at": "2019-11-12T16:43:26Z",
      "disk_in_mb": 1024,
      "guid": "13749565-ee33-4db3-a931-86229a76d1c5",
      "health_check": {
        "data": {
          "invocation_timeout": null,
          "timeout": null
        },
        "type": "port"
      },
      "instances": 1,
      "links": {
```

**Comment by mariash** [comment]
Hi @JimmyMa, what version of capi release and diego release are you using? I was not able to reproduce given the steps provided above. After restart `cf v3-ssh test-app` works for me.

My versions:
capi-release - 1.88.0
diego-release  - 2.40.0

**Comment by JimmyMa** [comment]
@mariash sorry, my fault about the reproduce steps (I have updated it), it should be below:

```
cf v3-ssh test_app  # this works fine
cf ssh test_app  # this doesn't work, with below error:
FAILED
Error opening SSH connection: ssh: handshake failed: ssh: unable to authenticate, attempted methods [none password], no supported methods remain
```

Could you try `cf ssh test-app`? thanks.

**Comment by sunjayBhatia** [comment]
@JimmyMa this is a known limitation of the `v6` CF cli, see: https://docs.cloudfoundry.org/devguide/deploy-apps/rolling-deploy.html#limitations

The CAPI team have weighed in here:
- https://cloudfoundry.slack.com/archives/C07C04W4Q/p1575407850231700
- https://cloudfoundry.slack.com/archives/CCRLX88DD/p1575470422310700

Also note, all `v3-*` commands are technically experimental

I'm going to close this issue as it is not technically a `diego-ssh` issue, rather a CF cli/CF api rough edge
